set(CMAKE_EXECUTABLE_SUFFIX .elf)
set(CMAKE_ASM_SOURCE_SUFFIX .s)
set(CMAKE_ASM_OUTPUT_EXTENSION .o)
set(CMAKE_C_OUTPUT_EXTENSION .o)
set(CMAKE_CXX_OUTPUT_EXTENSION .o)

set(CMAKE_C_FLAGS "" CACHE STRING "")
set(CMAKE_CXX_FLAGS "" CACHE STRING "")
set(CMAKE_ASM_FLAGS "" CACHE STRING "")
